### ISSUE TITLE
Maximum call stack size error

### ISSUE THREAD

**Issue by fiznool** [uber/npm-shrinkwrap#94]
```
npm-shrinkwrap
/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:197
  Object.keys(deps).forEach(function (d) {
         ^

RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:197:21)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
    at bfsify (/home/fiznool/.nvm/versions/node/v4.2.2/lib/node_modules/npm-shrinkwrap/node_modules/npm/lib/ls.js:217:10)
```

I admittedly have a large dependency graph, but a regular `npm shrinkwrap` handles it ok.

**Comment by martin-torhage** [comment]
I get the same error. Turns out that node's default stack size is only 984 kB (which seems low to me). By increasing it I got it to work. E.g: `node --stack_size=10240`

npm-shrinkwrap doesn't seem to pass arguments down to node. I don't know if this is something that can be changed in npm-shrinkwrap or if npm is blocking this. It doesn't seem like there is a way to configure node globally, so what you have to do is add a wrapper for node that calls the real node with the added stack_size argument.
```
$ cat bin/node
#!/bin/sh
/usr/local/opt/nvm/versions/node/v0.12.9/bin/node --stack_size=10240 $@
```

Is it possible to make npm-shrinkwrap to pass v8 options down to node?

**Comment by jscheid** [comment]
I'm getting the same error, this works for me:

    $ node --stack_size=10240 $(which npm-shrinkwrap)

**Comment by fiznool** [comment]
Thanks for this.

Maybe something could be added into the README for others who experience this issue?
